#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-l2-eth-infra-datatypes.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-l2-eth-infra-datatypes.yang


class ns(object):
    hash = 200921995

    id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-datatypes"

    uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-datatypes"

    prefix = "l2-eth-infra-datatypes"

    l2_eth_infra_datatypes_push2 = 4
    l2_eth_infra_datatypes_push2_ = "push2"
    l2_eth_infra_datatypes_match_default = 1
    l2_eth_infra_datatypes_match_default_ = "match-default"
    l2_eth_infra_datatypes_match_dot1ad_priority = 6
    l2_eth_infra_datatypes_match_dot1ad_priority_ = "match-dot1ad-priority"
    l2_eth_infra_datatypes_match_untagged = 2
    l2_eth_infra_datatypes_match_untagged_ = "match-untagged"
    l2_eth_infra_datatypes_pop1 = 1
    l2_eth_infra_datatypes_pop1_ = "pop1"
    l2_eth_infra_datatypes_match_dot1q = 3
    l2_eth_infra_datatypes_match_dot1q_ = "match-dot1q"
    l2_eth_infra_datatypes_native_with_cvlan_preservation = 65534
    l2_eth_infra_datatypes_native_with_cvlan_preservation_ = "native-with-cvlan-preservation"
    l2_eth_infra_datatypes_match_dot1q_priority = 5
    l2_eth_infra_datatypes_match_dot1q_priority_ = "match-dot1q-priority"
    l2_eth_infra_datatypes_match_dot1ad = 4
    l2_eth_infra_datatypes_match_dot1ad_ = "match-dot1ad"
    l2_eth_infra_datatypes_vlan_type_dot1q = 2
    l2_eth_infra_datatypes_vlan_type_dot1q_ = "vlan-type-dot1q"
    l2_eth_infra_datatypes_pop2 = 2
    l2_eth_infra_datatypes_pop2_ = "pop2"
    l2_eth_infra_datatypes_push1 = 3
    l2_eth_infra_datatypes_push1_ = "push1"
    l2_eth_infra_datatypes_translate2to1 = 7
    l2_eth_infra_datatypes_translate2to1_ = "translate2to1"
    l2_eth_infra_datatypes_native = 65535
    l2_eth_infra_datatypes_native_ = "native"
    l2_eth_infra_datatypes_translate2to2 = 8
    l2_eth_infra_datatypes_translate2to2_ = "translate2to2"
    l2_eth_infra_datatypes_vlan_type_dot1ad = 1
    l2_eth_infra_datatypes_vlan_type_dot1ad_ = "vlan-type-dot1ad"
    l2_eth_infra_datatypes_translate1to2 = 6
    l2_eth_infra_datatypes_translate1to2_ = "translate1to2"
    l2_eth_infra_datatypes_translate1to1 = 5
    l2_eth_infra_datatypes_translate1to1_ = "translate1to1"
    l2_eth_infra_datatypes_ppp_over_ethernet = 34915
    l2_eth_infra_datatypes_ppp_over_ethernet_ = "ppp-over-ethernet"
