#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nc-1.0.yang


class ns(object):
    hash = 2011875503

    id = "http://tail-f.com/ns/ned-id/cisco-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/cisco-nc-1.0"

    prefix = "cisco-nc-1.0"

    cisco_nc_10x2e0_cisco_nc_10x2e0 = 1413599745
    cisco_nc_10x2e0_cisco_nc_10x2e0_ = "cisco-nc-1.0"
