#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nc.yang


class ns(object):
    hash = 1634026686

    id = "http://tail-f.com/ns/ned-id/cisco-nc"

    uri = "http://tail-f.com/ns/ned-id/cisco-nc"

    prefix = "cisco-nc"

    cisco_nc_cisco_nc = 1207132395
    cisco_nc_cisco_nc_ = "cisco-nc"
    ned_id = 1207132395
    ned_id_ = "cisco-nc:cisco-nc"
