#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-types.yang


class ns(object):
    hash = 383236521

    id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/cisco-xr-types"

    uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/cisco-xr-types"

    prefix = "xr"

    xr_proprietary = 2
    xr_proprietary_ = "proprietary"
    xr_none = 0
    xr_none_ = "none"
    xr_md5 = 1
    xr_md5_ = "md5"
