#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ifmgr-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ifmgr-cfg.yang


class ns(object):
    hash = 1984872371

    id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"

    uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg"

    prefix = "ifmgr-cfg"

    ifmgr_cfg_interface_mode_non_physical = 1525547646
    ifmgr_cfg_interface_mode_non_physical_ = "interface-mode-non-physical"
    ifmgr_cfg_specify_rp = 5
    ifmgr_cfg_specify_rp_ = "specify-rp"
    ifmgr_cfg_default_values = 0
    ifmgr_cfg_default_values_ = "default-values"
    ifmgr_cfg_mtu = 1751455506
    ifmgr_cfg_mtu_ = "mtu"
    ifmgr_cfg_args = 578380655
    ifmgr_cfg_args_ = "args"
    ifmgr_cfg_link_status = 2137463011
    ifmgr_cfg_link_status_ = "link-status"
    ifmgr_cfg_shutdown = 460723287
    ifmgr_cfg_shutdown_ = "shutdown"
    ifmgr_cfg_suppress_time = 1030211810
    ifmgr_cfg_suppress_time_ = "suppress-time"
    ifmgr_cfg_default = 0
    ifmgr_cfg_default_ = "default"
    ifmgr_cfg_interface_configuration = 1340857377
    ifmgr_cfg_interface_configuration_ = "interface-configuration"
    ifmgr_cfg_specify_all = 4
    ifmgr_cfg_specify_all_ = "specify-all"
    ifmgr_cfg_dampening = 1049243107
    ifmgr_cfg_dampening_ = "dampening"
    ifmgr_cfg_interface_name = 1322899300
    ifmgr_cfg_interface_name_ = "interface-name"
    ifmgr_cfg_specify_half_life = 1
    ifmgr_cfg_specify_half_life_ = "specify-half-life"
    ifmgr_cfg_mtus = 1903045155
    ifmgr_cfg_mtus_ = "mtus"
    ifmgr_cfg_l2_transport = 3
    ifmgr_cfg_l2_transport_ = "l2-transport"
    ifmgr_cfg_description = 202559156
    ifmgr_cfg_description_ = "description"
    ifmgr_cfg_maintenance = 1
    ifmgr_cfg_maintenance_ = "maintenance"
    ifmgr_cfg_suppress_threshold = 1022099602
    ifmgr_cfg_suppress_threshold_ = "suppress-threshold"
    ifmgr_cfg_software_interfaces = 2
    ifmgr_cfg_software_interfaces_ = "software-interfaces"
    ifmgr_cfg_capsulation_options = 1165673411
    ifmgr_cfg_capsulation_options_ = "capsulation-options"
    ifmgr_cfg_interface_virtual = 366954786
    ifmgr_cfg_interface_virtual_ = "interface-virtual"
    ifmgr_cfg_multipoint = 2
    ifmgr_cfg_multipoint_ = "multipoint"
    ifmgr_cfg_global_interface_configuration = 628731272
    ifmgr_cfg_global_interface_configuration_ = "global-interface-configuration"
    ifmgr_cfg_disable = 1
    ifmgr_cfg_disable_ = "disable"
    ifmgr_cfg_secondary_admin_state = 2116682695
    ifmgr_cfg_secondary_admin_state_ = "secondary-admin-state"
    ifmgr_cfg_bandwidth = 82191353
    ifmgr_cfg_bandwidth_ = "bandwidth"
    ifmgr_cfg_half_life = 722675026
    ifmgr_cfg_half_life_ = "half-life"
    ifmgr_cfg_point_to_point = 1
    ifmgr_cfg_point_to_point_ = "point-to-point"
    ifmgr_cfg_owner = 206925960
    ifmgr_cfg_owner_ = "owner"
    ifmgr_cfg_encapsulation = 436115321
    ifmgr_cfg_encapsulation_ = "encapsulation"
    ifmgr_cfg_restart_penalty = 354955372
    ifmgr_cfg_restart_penalty_ = "restart-penalty"
    ifmgr_cfg_active = 124277386
    ifmgr_cfg_active_ = "active"
    ifmgr_cfg_interface_configurations = 1818562055
    ifmgr_cfg_interface_configurations_ = "interface-configurations"
    ifmgr_cfg_reuse_threshold = 1727092908
    ifmgr_cfg_reuse_threshold_ = "reuse-threshold"
