/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/mef-global@2018-07-11.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.evc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module mef-global@2018-07-11.yang */
public class mefGlobal extends ConfNamespace {
    public static final int hash = 1320067688;
    public int hash() {
        return mefGlobal.hash;
    }

    public static final String id = "urn:mef:yang:mef-global";
    public String id() {
        return mefGlobal.id;
    }

    public static final String uri = "urn:mef:yang:mef-global";
    public String uri() {
        return mefGlobal.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(mefGlobal.uri);
    }

    public static final String prefix = "mef-global";
    public String prefix() {
        return mefGlobal.prefix;
    }

    public mefGlobal() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _l2cp_eec_id = 1734847993;
    public static final String _l2cp_eec_id_ = "l2cp-eec-id";
    public static final int    _cir = 38343320;
    public static final String _cir_ = "cir";
    public static final int    _ifdv_indicator = 1085790165;
    public static final String _ifdv_indicator_ = "ifdv-indicator";
    public static final int    _frame_loss_indicator = 1365151546;
    public static final String _frame_loss_indicator_ = "frame-loss-indicator";
    public static final int    _fdr = 847230039;
    public static final String _fdr_ = "fdr";
    public static final int    _simple_or_subtypes = 768972403;
    public static final String _simple_or_subtypes_ = "simple-or-subtypes";
    public static final int    _ifdv = 248377710;
    public static final String _ifdv_ = "ifdv";
    public static final int    _one_way_composite_pm = 1266937751;
    public static final String _one_way_composite_pm_ = "one-way-composite-pm";
    public static final int    _color_dscp = 1834969645;
    public static final String _color_dscp_ = "color-dscp";
    public static final int    _cos_dscp = 1579058152;
    public static final String _cos_dscp_ = "cos-dscp";
    public static final int    _evc_cos_name = 571197252;
    public static final String _evc_cos_name_ = "evc-cos-name";
    public static final int    _time_interval = 953195257;
    public static final String _time_interval_ = "time-interval";
    public static final int    _color_dei = 1249774624;
    public static final String _color_dei_ = "color-dei";
    public static final int    _ipv6_dscp = 888092426;
    public static final String _ipv6_dscp_ = "ipv6-dscp";
    public static final int    _cos_profiles = 1123448114;
    public static final String _cos_profiles_ = "cos-profiles";
    public static final int    _mef_global = 1299431098;
    public static final String _mef_global_ = "mef-global";
    public static final int    _cos_names_profiles = 1960567544;
    public static final String _cos_names_profiles_ = "cos-names-profiles";
    public static final int    _one_way_group_availability_pm = 339711056;
    public static final String _one_way_group_availability_pm_ = "one-way-group-availability-pm";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _availability = 1596189949;
    public static final String _availability_ = "availability";
    public static final int    _color = 726677026;
    public static final String _color_ = "color";
    public static final int    _ipv6_dscps = 1408523675;
    public static final String _ipv6_dscps_ = "ipv6-dscps";
    public static final int    _hli = 565080637;
    public static final String _hli_ = "hli";
    public static final int    _cpi_threshold_u = 518584693;
    public static final String _cpi_threshold_u_ = "cpi-threshold-u";
    public static final int    _l2cp_eec_profiles = 1350090319;
    public static final String _l2cp_eec_profiles_ = "l2cp-eec-profiles";
    public static final int    _color_mapping_profiles = 920471952;
    public static final String _color_mapping_profiles_ = "color-mapping-profiles";
    public static final int    _flr = 1808970540;
    public static final String _flr_ = "flr";
    public static final int    _profile = 1538168517;
    public static final String _profile_ = "profile";
    public static final int    _frame_delay_indicator = 1805339535;
    public static final String _frame_delay_indicator_ = "frame-delay-indicator";
    public static final int    _one_way_frame_delay_range_pm = 1710908029;
    public static final String _one_way_frame_delay_range_pm_ = "one-way-frame-delay-range-pm";
    public static final int    _evc = 748950332;
    public static final String _evc_ = "evc";
    public static final int    _one_way_availability_pm = 1609027590;
    public static final String _one_way_availability_pm_ = "one-way-availability-pm";
    public static final int    _pcp_value = 963428065;
    public static final String _pcp_value_ = "pcp-value";
    public static final int    _one_way_consecutive_high_loss_interval_pm = 876734708;
    public static final String _one_way_consecutive_high_loss_interval_pm_ = "one-way-consecutive-high-loss-interval-pm";
    public static final int    _pcp = 236583976;
    public static final String _pcp_ = "pcp";
    public static final int    _one_way_frame_delay_pm = 1408138895;
    public static final String _one_way_frame_delay_pm_ = "one-way-frame-delay-pm";
    public static final int    _pm_entry = 995696235;
    public static final String _pm_entry_ = "pm-entry";
    public static final int    _eec_name = 307147103;
    public static final String _eec_name_ = "eec-name";
    public static final int    _bwp_flow_parameter_profiles = 6083892;
    public static final String _bwp_flow_parameter_profiles_ = "bwp-flow-parameter-profiles";
    public static final int    _delta_t = 1976159526;
    public static final String _delta_t_ = "delta-t";
    public static final int    _color_id = 886040390;
    public static final String _color_id_ = "color-id";
    public static final int    _simple_option = 501127768;
    public static final String _simple_option_ = "simple-option";
    public static final int    _ipv4_dscp = 2060727226;
    public static final String _ipv4_dscp_ = "ipv4-dscp";
    public static final int    _l2cp_peering = 1088645119;
    public static final String _l2cp_peering_ = "l2cp-peering";
    public static final int    _dest_mac_addr = 167904204;
    public static final String _dest_mac_addr_ = "dest-mac-addr";
    public static final int    _default_pcp_color_name = 1462726252;
    public static final String _default_pcp_color_name_ = "default-pcp-color-name";
    public static final int    _subtype = 1955371587;
    public static final String _subtype_ = "subtype";
    public static final int    _l2cp_cos_id = 1841859854;
    public static final String _l2cp_cos_id_ = "l2cp-cos-id";
    public static final int    _consecutive_number_p = 1914859228;
    public static final String _consecutive_number_p_ = "consecutive-number-p";
    public static final int    _cos_name = 813970987;
    public static final String _cos_name_ = "cos-name";
    public static final int    _dei = 1423139725;
    public static final String _dei_ = "dei";
    public static final int    _one_way_fd_threshold = 350208427;
    public static final String _one_way_fd_threshold_ = "one-way-fd-threshold";
    public static final int    _eir = 61411079;
    public static final String _eir_ = "eir";
    public static final int    _map_entry = 163806575;
    public static final String _map_entry_ = "map-entry";
    public static final int    _min_number_of_uni_pair_sets = 366939381;
    public static final String _min_number_of_uni_pair_sets_ = "min-number-of-uni-pair-sets";
    public static final int    _ipv4_dscps = 1769433022;
    public static final String _ipv4_dscps_ = "ipv4-dscps";
    public static final int    _subtypes_option = 1897702101;
    public static final String _subtypes_option_ = "subtypes-option";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _color_pcp = 223341123;
    public static final String _color_pcp_ = "color-pcp";
    public static final int    _color_evc = 944475954;
    public static final String _color_evc_ = "color-evc";
    public static final int    _l2cp_peerings = 690647614;
    public static final String _l2cp_peerings_ = "l2cp-peerings";
    public static final int    _one_way_ifdv_threshold = 1539659375;
    public static final String _one_way_ifdv_threshold_ = "one-way-ifdv-threshold";
    public static final int    _chli = 827124445;
    public static final String _chli_ = "chli";
    public static final int    _evc_color_name = 1609116664;
    public static final String _evc_color_name_ = "evc-color-name";
    public static final int    _percentile = 378849660;
    public static final String _percentile_ = "percentile";
    public static final int    _eir_max = 472208704;
    public static final String _eir_max_ = "eir-max";
    public static final int    _one_way_performance_metric = 965655269;
    public static final String _one_way_performance_metric_ = "one-way-performance-metric";
    public static final int    _objective = 782005216;
    public static final String _objective_ = "objective";
    public static final int    _cpm = 2137614363;
    public static final String _cpm_ = "cpm";
    public static final int    _map_entries = 212051463;
    public static final String _map_entries_ = "map-entries";
    public static final int    _dscp_value = 935408468;
    public static final String _dscp_value_ = "dscp-value";
    public static final int    _default_pcp_eec_name = 1112188333;
    public static final String _default_pcp_eec_name_ = "default-pcp-eec-name";
    public static final int    _coupling_enabled = 449227583;
    public static final String _coupling_enabled_ = "coupling-enabled";
    public static final int    _group_avail = 1793907391;
    public static final String _group_avail_ = "group-avail";
    public static final int    _default_ipv6_eec_name = 1240127298;
    public static final String _default_ipv6_eec_name_ = "default-ipv6-eec-name";
    public static final int    _discard = 664427145;
    public static final String _discard_ = "discard";
    public static final int    _pm_cos_name_entry = 2016541922;
    public static final String _pm_cos_name_entry_ = "pm-cos-name-entry";
    public static final int    _l2cp_peering_profiles = 947319018;
    public static final String _l2cp_peering_profiles_ = "l2cp-peering-profiles";
    public static final int    _cbs = 857366942;
    public static final String _cbs_ = "cbs";
    public static final int    _one_way_inter_frame_delay_variation_pm = 188142916;
    public static final String _one_way_inter_frame_delay_variation_pm_ = "one-way-inter-frame-delay-variation-pm";
    public static final int    _cos_evc = 53820491;
    public static final String _cos_evc_ = "cos-evc";
    public static final int    _cos_id = 1247709842;
    public static final String _cos_id_ = "cos-id";
    public static final int    _dscp = 1118112132;
    public static final String _dscp_ = "dscp";
    public static final int    _ebs = 2072008753;
    public static final String _ebs_ = "ebs";
    public static final int    _eec_profiles = 1459881255;
    public static final String _eec_profiles_ = "eec-profiles";
    public static final int    _default_pcp_cos_name = 25896066;
    public static final String _default_pcp_cos_name_ = "default-pcp-cos-name";
    public static final int    _l2cp_cos_map_profiles = 252261520;
    public static final String _l2cp_cos_map_profiles_ = "l2cp-cos-map-profiles";
    public static final int    _sls_profiles = 1261933243;
    public static final String _sls_profiles_ = "sls-profiles";
    public static final int    _mfd = 80951565;
    public static final String _mfd_ = "mfd";
    public static final int    _color_mode = 585625747;
    public static final String _color_mode_ = "color-mode";
    public static final int    _default_ipv4_cos_name = 75540207;
    public static final String _default_ipv4_cos_name_ = "default-ipv4-cos-name";
    public static final int    _subtypes = 1545577800;
    public static final String _subtypes_ = "subtypes";
    public static final int    _default_ipv4_eec_name = 738259513;
    public static final String _default_ipv4_eec_name_ = "default-ipv4-eec-name";
    public static final int    _eec_pcp = 346719947;
    public static final String _eec_pcp_ = "eec-pcp";
    public static final int    _cir_max = 1022527967;
    public static final String _cir_max_ = "cir-max";
    public static final int    _consecutive_interval_n = 1499262048;
    public static final String _consecutive_interval_n_ = "consecutive-interval-n";
    public static final int    _threshold_c = 858568406;
    public static final String _threshold_c_ = "threshold-c";
    public static final int    _pm_entries = 1548565644;
    public static final String _pm_entries_ = "pm-entries";
    public static final int    _pcps = 1829124177;
    public static final String _pcps_ = "pcps";
    public static final int    _default_dscp_color_name = 663166555;
    public static final String _default_dscp_color_name_ = "default-dscp-color-name";
    public static final int    _one_way_mean_frame_delay_pm = 1542274802;
    public static final String _one_way_mean_frame_delay_pm_ = "one-way-mean-frame-delay-pm";
    public static final int    _pm_cos_name_entries = 1546523111;
    public static final String _pm_cos_name_entries_ = "pm-cos-name-entries";
    public static final int    _eec_dscp = 697537132;
    public static final String _eec_dscp_ = "eec-dscp";
    public static final int    _fd = 458855098;
    public static final String _fd_ = "fd";
    public static final int    _frame_pair_separation = 1654725241;
    public static final String _frame_pair_separation_ = "frame-pair-separation";
    public static final int    _default_ipv6_cos_name = 638157734;
    public static final String _default_ipv6_cos_name_ = "default-ipv6-cos-name";
    public static final int    _eec_id = 1633194947;
    public static final String _eec_id_ = "eec-id";
    public static final int    _cos_pcp = 183072091;
    public static final String _cos_pcp_ = "cos-pcp";
    public static final int    _one_way_frame_loss_ratio_pm = 310310455;
    public static final String _one_way_frame_loss_ratio_pm_ = "one-way-frame-loss-ratio-pm";
    public static final int    _discard_or_cos_name = 407469625;
    public static final String _discard_or_cos_name_ = "discard-or-cos-name";
    public static final int    _protocol_id = 26418453;
    public static final String _protocol_id_ = "protocol-id";
    public static final int    _one_way_high_loss_interval_pm = 466070713;
    public static final String _one_way_high_loss_interval_pm_ = "one-way-high-loss-interval-pm";
}
