/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/mef-legato-services@2018-07-11.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.evc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module mef-legato-services@2018-07-11.yang */
public class mefLegatoServices extends ConfNamespace {
    public static final int hash = 1459416473;
    public int hash() {
        return mefLegatoServices.hash;
    }

    public static final String id = "urn:mef:yang:mef-legato-services";
    public String id() {
        return mefLegatoServices.id;
    }

    public static final String uri = "urn:mef:yang:mef-legato-services";
    public String uri() {
        return mefLegatoServices.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(mefLegatoServices.uri);
    }

    public static final String prefix = "mef-services";
    public String prefix() {
        return mefLegatoServices.prefix;
    }

    public mefLegatoServices() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ingress_bw_profile_per_evc = 150605994;
    public static final String _ingress_bw_profile_per_evc_ = "ingress-bw-profile-per-evc";
    public static final int    _inclusions = 2112234748;
    public static final String _inclusions_ = "inclusions";
    public static final int    _egress_bw_profile_per_evc = 1049352521;
    public static final String _egress_bw_profile_per_evc_ = "egress-bw-profile-per-evc";
    public static final int    _test_meg_enabled = 1478088264;
    public static final String _test_meg_enabled_ = "test-meg-enabled";
    public static final int    _end_point_pair = 416979547;
    public static final String _end_point_pair_ = "end-point-pair";
    public static final int    _standalone = 1141494651;
    public static final String _standalone_ = "standalone";
    public static final int    _source_mac_address_limit_time_interval = 1860490029;
    public static final String _source_mac_address_limit_time_interval_ = "source-mac-address-limit-time-interval";
    public static final int    _max_num_of_evc_end_point = 1351100923;
    public static final String _max_num_of_evc_end_point_ = "max-num-of-evc-end-point";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _envelope_id = 1487875498;
    public static final String _envelope_id_ = "envelope-id";
    public static final int    _carrier_ethernet_sls = 1806500088;
    public static final String _carrier_ethernet_sls_ = "carrier-ethernet-sls";
    public static final int    _service_state = 2127816998;
    public static final String _service_state_ = "service-state";
    public static final int    _sls_id = 1677944964;
    public static final String _sls_id_ = "sls-id";
    public static final int    _broadcast_frame_delivery = 285097802;
    public static final String _broadcast_frame_delivery_ = "broadcast-frame-delivery";
    public static final int    _carrier_ethernet = 1874836565;
    public static final String _carrier_ethernet_ = "carrier-ethernet";
    public static final int    _bwp_flow_per_cos = 254919184;
    public static final String _bwp_flow_per_cos_ = "bwp-flow-per-cos";
    public static final int    _unicast_frame_delivery = 1483313743;
    public static final String _unicast_frame_delivery_ = "unicast-frame-delivery";
    public static final int    _end_point2 = 879607132;
    public static final String _end_point2_ = "end-point2";
    public static final int    _ingress_bwp_choices = 189936631;
    public static final String _ingress_bwp_choices_ = "ingress-bwp-choices";
    public static final int    _evc = 748950332;
    public static final String _evc_ = "evc";
    public static final int    _envelope = 1659842116;
    public static final String _envelope_ = "envelope";
    public static final int    _rank = 1968605785;
    public static final String _rank_ = "rank";
    public static final int    _eec_identifier = 87922565;
    public static final String _eec_identifier_ = "eec-identifier";
    public static final int    _pm_entry = 995696235;
    public static final String _pm_entry_ = "pm-entry";
    public static final int    _eec_name = 307147103;
    public static final String _eec_name_ = "eec-name";
    public static final int    _user_label = 392138510;
    public static final String _user_label_ = "user-label";
    public static final int    _bw_profile_flow_parameters = 64514602;
    public static final String _bw_profile_flow_parameters_ = "bw-profile-flow-parameters";
    public static final int    _cos_name = 813970987;
    public static final String _cos_name_ = "cos-name";
    public static final int    _end_point1 = 653189209;
    public static final String _end_point1_ = "end-point1";
    public static final int    _connection_type = 192228205;
    public static final String _connection_type_ = "connection-type";
    public static final int    _ce_vlans = 1657267537;
    public static final String _ce_vlans_ = "ce-vlans";
    public static final int    _subscriber_services = 462043399;
    public static final String _subscriber_services_ = "subscriber-services";
    public static final int    _evc_id = 1242210050;
    public static final String _evc_id_ = "evc-id";
    public static final int    _cos_entries = 2064160067;
    public static final String _cos_entries_ = "cos-entries";
    public static final int    _egress_bwp_per_evc_option = 1491173959;
    public static final String _egress_bwp_per_evc_option_ = "egress-bwp-per-evc-option";
    public static final int    _multicast_frame_delivery = 924796069;
    public static final String _multicast_frame_delivery_ = "multicast-frame-delivery";
    public static final int    _ingress_bwp_per_cos_option = 644323624;
    public static final String _ingress_bwp_per_cos_option_ = "ingress-bwp-per-cos-option";
    public static final int    _bwp_flow_per_eec = 1687915165;
    public static final String _bwp_flow_per_eec_ = "bwp-flow-per-eec";
    public static final int    _svc_type = 1825557732;
    public static final String _svc_type_ = "svc-type";
    public static final int    _ce_vlan_id_preservation = 264426404;
    public static final String _ce_vlan_id_preservation_ = "ce-vlan-id-preservation";
    public static final int    _source_mac_address_limit = 996754653;
    public static final String _source_mac_address_limit_ = "source-mac-address-limit";
    public static final int    _cos_identifier = 1826623440;
    public static final String _cos_identifier_ = "cos-identifier";
    public static final int    _subscriber_meg_mip_enabled = 1335279499;
    public static final String _subscriber_meg_mip_enabled_ = "subscriber-meg-mip-enabled";
    public static final int    _set_of_end_point_pairs = 218042592;
    public static final String _set_of_end_point_pairs_ = "set-of-end-point-pairs";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _ingress_bwp_per_evc = 839612363;
    public static final String _ingress_bwp_per_evc_ = "ingress-bwp-per-evc";
    public static final int    _end_points = 1890096153;
    public static final String _end_points_ = "end-points";
    public static final int    _pm_entry_id = 492549486;
    public static final String _pm_entry_id_ = "pm-entry-id";
    public static final int    _egress_bwp_per_eec = 100621810;
    public static final String _egress_bwp_per_eec_ = "egress-bwp-per-eec";
    public static final int    _egress_bwp_per_evc = 272096996;
    public static final String _egress_bwp_per_evc_ = "egress-bwp-per-evc";
    public static final int    _sls_uni_exclusions = 372340918;
    public static final String _sls_uni_exclusions_ = "sls-uni-exclusions";
    public static final int    _ingress_bwp_per_cos = 133418617;
    public static final String _ingress_bwp_per_cos_ = "ingress-bwp-per-cos";
    public static final int    _sets_of_end_point_pairs = 1636276909;
    public static final String _sets_of_end_point_pairs_ = "sets-of-end-point-pairs";
    public static final int    _egress_bwp_per_eec_option = 1088167613;
    public static final String _egress_bwp_per_eec_option_ = "egress-bwp-per-eec-option";
    public static final int    _uni_id = 114857507;
    public static final String _uni_id_ = "uni-id";
    public static final int    _ce_vlan_pcp_preservation = 709521737;
    public static final String _ce_vlan_pcp_preservation_ = "ce-vlan-pcp-preservation";
    public static final int    _cos_names = 949117268;
    public static final String _cos_names_ = "cos-names";
    public static final int    _sls_uni = 31433938;
    public static final String _sls_uni_ = "sls-uni";
    public static final int    _egress_bwp_choices = 2100372492;
    public static final String _egress_bwp_choices_ = "egress-bwp-choices";
    public static final int    _end_point_pairs = 775585459;
    public static final String _end_point_pairs_ = "end-point-pairs";
    public static final int    _sls_uni_inclusions = 265728392;
    public static final String _sls_uni_inclusions_ = "sls-uni-inclusions";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _end_point = 935030957;
    public static final String _end_point_ = "end-point";
    public static final int    _exclusions = 930863306;
    public static final String _exclusions_ = "exclusions";
    public static final int    _pm_entries = 1548565644;
    public static final String _pm_entries_ = "pm-entries";
    public static final int    _egress_bw_profile_per_eec = 1858179695;
    public static final String _egress_bw_profile_per_eec_ = "egress-bw-profile-per-eec";
    public static final int    _evc_end_point_id = 1042230787;
    public static final String _evc_end_point_id_ = "evc-end-point-id";
    public static final int    _ingress_bwp_per_evc_option = 1903908144;
    public static final String _ingress_bwp_per_evc_option_ = "ingress-bwp-per-evc-option";
    public static final int    _admin_state = 1519849494;
    public static final String _admin_state_ = "admin-state";
    public static final int    _ce_vlan_dei_preservation = 295709744;
    public static final String _ce_vlan_dei_preservation_ = "ce-vlan-dei-preservation";
    public static final int    _mef_services = 1489667662;
    public static final String _mef_services_ = "mef-services";
    public static final int    _ce_vlan = 1866019202;
    public static final String _ce_vlan_ = "ce-vlan";
    public static final int    _cos_entry = 573242955;
    public static final String _cos_entry_ = "cos-entry";
    public static final int    _ingress_bw_profile_per_cos = 703145606;
    public static final String _ingress_bw_profile_per_cos_ = "ingress-bw-profile-per-cos";
    public static final int    _start_time = 84038180;
    public static final String _start_time_ = "start-time";
    public static final int    _color_identifier = 23109277;
    public static final String _color_identifier_ = "color-identifier";
    public static final int    _max_frame_size = 1333604257;
    public static final String _max_frame_size_ = "max-frame-size";
}
