/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/mef-legato-interfaces@2018-07-11.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.evc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module mef-legato-interfaces@2018-07-11.yang */
public class mefLegatoInterfaces extends ConfNamespace {
    public static final int hash = 2028751775;
    public int hash() {
        return mefLegatoInterfaces.hash;
    }

    public static final String id = "urn:mef:yang:mef-legato-interfaces";
    public String id() {
        return mefLegatoInterfaces.id;
    }

    public static final String uri = "urn:mef:yang:mef-legato-interfaces";
    public String uri() {
        return mefLegatoInterfaces.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(mefLegatoInterfaces.uri);
    }

    public static final String prefix = "mef-interfaces";
    public String prefix() {
        return mefLegatoInterfaces.prefix;
    }

    public mefLegatoInterfaces() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sync_mode = 1504526876;
    public static final String _sync_mode_ = "sync-mode";
    public static final int    _ingress_envelopes = 18131315;
    public static final String _ingress_envelopes_ = "ingress-envelopes";
    public static final int    _ieee8023_phy = 20725070;
    public static final String _ieee8023_phy_ = "ieee8023-phy";
    public static final int    _standalone = 1141494651;
    public static final String _standalone_ = "standalone";
    public static final int    _mef_interfaces = 1714973030;
    public static final String _mef_interfaces_ = "mef-interfaces";
    public static final int    _ingress_bwp_per_uni = 1613838341;
    public static final String _ingress_bwp_per_uni_ = "ingress-bwp-per-uni";
    public static final int    _portconv_map_entry = 1803696646;
    public static final String _portconv_map_entry_ = "portconv-map-entry";
    public static final int    _envelope_id = 1487875498;
    public static final String _envelope_id_ = "envelope-id";
    public static final int    _max_num_of_evcs = 1520441487;
    public static final String _max_num_of_evcs_ = "max-num-of-evcs";
    public static final int    _carrier_ethernet = 1874836565;
    public static final String _carrier_ethernet_ = "carrier-ethernet";
    public static final int    _envelope = 1659842116;
    public static final String _envelope_ = "envelope";
    public static final int    _rank = 1968605785;
    public static final String _rank_ = "rank";
    public static final int    _l2cp_peering = 1088645119;
    public static final String _l2cp_peering_ = "l2cp-peering";
    public static final int    _link_number = 1726485980;
    public static final String _link_number_ = "link-number";
    public static final int    _parameters = 716273249;
    public static final String _parameters_ = "parameters";
    public static final int    _bw_profile_flow_parameters = 64514602;
    public static final String _bw_profile_flow_parameters_ = "bw-profile-flow-parameters";
    public static final int    _subscriber_interfaces = 449780956;
    public static final String _subscriber_interfaces_ = "subscriber-interfaces";
    public static final int    _default_ce_vlan_id = 1761643439;
    public static final String _default_ce_vlan_id_ = "default-ce-vlan-id";
    public static final int    _bwp_flow = 113425636;
    public static final String _bwp_flow_ = "bwp-flow";
    public static final int    _uni_meg_enabled = 1268512327;
    public static final String _uni_meg_enabled_ = "uni-meg-enabled";
    public static final int    _token_share_enabled = 1910993979;
    public static final String _token_share_enabled_ = "token-share-enabled";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _vid = 1545846517;
    public static final String _vid_ = "vid";
    public static final int    _uni = 261020109;
    public static final String _uni_ = "uni";
    public static final int    _operational_state = 1839284571;
    public static final String _operational_state_ = "operational-state";
    public static final int    _service_multiplexing_enabled = 1388120782;
    public static final String _service_multiplexing_enabled_ = "service-multiplexing-enabled";
    public static final int    _port_convid_to_agglink_map = 1037311010;
    public static final String _port_convid_to_agglink_map_ = "port-convid-to-agglink-map";
    public static final int    _links = 159989304;
    public static final String _links_ = "links";
    public static final int    _coupling_enabled = 449227583;
    public static final String _coupling_enabled_ = "coupling-enabled";
    public static final int    _portconv_map_entries = 2042586606;
    public static final String _portconv_map_entries_ = "portconv-map-entries";
    public static final int    _bundling_enabled = 1386947029;
    public static final String _bundling_enabled_ = "bundling-enabled";
    public static final int    _link_oam_enabled = 2100794163;
    public static final String _link_oam_enabled_ = "link-oam-enabled";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _physical_layers = 1731219845;
    public static final String _physical_layers_ = "physical-layers";
    public static final int    _default_links = 1517533447;
    public static final String _default_links_ = "default-links";
    public static final int    _uni_id = 114857507;
    public static final String _uni_id_ = "uni-id";
    public static final int    _default_link = 965897415;
    public static final String _default_link_ = "default-link";
    public static final int    _egress_envelopes = 445550959;
    public static final String _egress_envelopes_ = "egress-envelopes";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _bwp_flows = 1165409643;
    public static final String _bwp_flows_ = "bwp-flows";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _link_aggregation = 955906427;
    public static final String _link_aggregation_ = "link-aggregation";
    public static final int    _admin_state = 1519849494;
    public static final String _admin_state_ = "admin-state";
    public static final int    _egress_bw_profile_per_uni = 1460262430;
    public static final String _egress_bw_profile_per_uni_ = "egress-bw-profile-per-uni";
    public static final int    _all_to_one_bundling_enabled = 1360761231;
    public static final String _all_to_one_bundling_enabled_ = "all-to-one-bundling-enabled";
    public static final int    _elmi_enabled = 417452446;
    public static final String _elmi_enabled_ = "elmi-enabled";
    public static final int    _options = 268171404;
    public static final String _options_ = "options";
    public static final int    _l2cp_address_set = 1797172840;
    public static final String _l2cp_address_set_ = "l2cp-address-set";
    public static final int    _max_frame_size = 1333604257;
    public static final String _max_frame_size_ = "max-frame-size";
}
