/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/mef-types@2018-07-11.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.evc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module mef-types@2018-07-11.yang */
public class mefTypes extends ConfNamespace {
    public static final int hash = 1636170091;
    public int hash() {
        return mefTypes.hash;
    }

    public static final String id = "urn:mef:yang:mef-types";
    public String id() {
        return mefTypes.id;
    }

    public static final String uri = "urn:mef:yang:mef-types";
    public String uri() {
        return mefTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(mefTypes.uri);
    }

    public static final String prefix = "mef-types";
    public String prefix() {
        return mefTypes.prefix;
    }

    public mefTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ieee8023_100BASE_BX10 = 873053431;
    public static final String _ieee8023_100BASE_BX10_ = "ieee8023-100BASE-BX10";
    public static final int    _ieee8023_10GBASE_E = 1125019918;
    public static final String _ieee8023_10GBASE_E_ = "ieee8023-10GBASE-E";
    public static final int    _ieee8023_1000BASE_KX = 1171659022;
    public static final String _ieee8023_1000BASE_KX_ = "ieee8023-1000BASE-KX";
    public static final int    _ieee8023_10BASE_T = 1733753057;
    public static final String _ieee8023_10BASE_T_ = "ieee8023-10BASE-T";
    public static final int    _ieee8023_10BASE_F = 315990986;
    public static final String _ieee8023_10BASE_F_ = "ieee8023-10BASE-F";
    public static final int    _ieee8023_10GBASE_CX4 = 935336055;
    public static final String _ieee8023_10GBASE_CX4_ = "ieee8023-10GBASE-CX4";
    public static final int    _ieee8023_10GBASE_KX4 = 1042515651;
    public static final String _ieee8023_10GBASE_KX4_ = "ieee8023-10GBASE-KX4";
    public static final int    _ieee8023_1000BASE_LX10 = 856993996;
    public static final String _ieee8023_1000BASE_LX10_ = "ieee8023-1000BASE-LX10";
    public static final int    _ieee8023_10BASE5 = 1589160116;
    public static final String _ieee8023_10BASE5_ = "ieee8023-10BASE5";
    public static final int    _ieee8023_1000BASE_LX = 440798416;
    public static final String _ieee8023_1000BASE_LX_ = "ieee8023-1000BASE-LX";
    public static final int    _ieee8023_10GBASE_LRM = 937504819;
    public static final String _ieee8023_10GBASE_LRM_ = "ieee8023-10GBASE-LRM";
    public static final int    _ieee8023_10GBASE_LX4 = 1663491179;
    public static final String _ieee8023_10GBASE_LX4_ = "ieee8023-10GBASE-LX4";
    public static final int    _ieee8023_100BASE_TX = 866950928;
    public static final String _ieee8023_100BASE_TX_ = "ieee8023-100BASE-TX";
    public static final int    _ieee8023_100BASE_T4 = 1886529930;
    public static final String _ieee8023_100BASE_T4_ = "ieee8023-100BASE-T4";
    public static final int    _ieee8023_100BASE_LX10 = 172352324;
    public static final String _ieee8023_100BASE_LX10_ = "ieee8023-100BASE-LX10";
    public static final int    _ieee8023_100BASE_T2 = 460183121;
    public static final String _ieee8023_100BASE_T2_ = "ieee8023-100BASE-T2";
    public static final int    _ieee8023_10GBASE_LR = 187252530;
    public static final String _ieee8023_10GBASE_LR_ = "ieee8023-10GBASE-LR";
    public static final int    _ieee8023_100BASE_T = 367607563;
    public static final String _ieee8023_100BASE_T_ = "ieee8023-100BASE-T";
    public static final int    _ieee8023_10GBASE_LW = 199918817;
    public static final String _ieee8023_10GBASE_LW_ = "ieee8023-10GBASE-LW";
    public static final int    _ieee8023_1000BASE_PX_U = 2121584128;
    public static final String _ieee8023_1000BASE_PX_U_ = "ieee8023-1000BASE-PX-U";
    public static final int    _ieee8023_1000BASE_SX = 1344115270;
    public static final String _ieee8023_1000BASE_SX_ = "ieee8023-1000BASE-SX";
    public static final int    _ieee8023_10PASS_TS = 1708182496;
    public static final String _ieee8023_10PASS_TS_ = "ieee8023-10PASS-TS";
    public static final int    _ieee_8023_interface_type = 180355228;
    public static final String _ieee_8023_interface_type_ = "ieee-8023-interface-type";
    public static final int    _ieee8023_10GBASE_ER = 982565901;
    public static final String _ieee8023_10GBASE_ER_ = "ieee8023-10GBASE-ER";
    public static final int    _ieee8023_1000BASE_PX_D = 1650532526;
    public static final String _ieee8023_1000BASE_PX_D_ = "ieee8023-1000BASE-PX-D";
    public static final int    _ieee8023_10BASE2 = 1598219356;
    public static final String _ieee8023_10BASE2_ = "ieee8023-10BASE2";
    public static final int    _ieee8023_10BROAD36 = 262302638;
    public static final String _ieee8023_10BROAD36_ = "ieee8023-10BROAD36";
    public static final int    _ieee8023_10GBASE_KR = 1829151584;
    public static final String _ieee8023_10GBASE_KR_ = "ieee8023-10GBASE-KR";
    public static final int    _ieee8023_10GBASE_PR = 1083279828;
    public static final String _ieee8023_10GBASE_PR_ = "ieee8023-10GBASE-PR";
    public static final int    _ieee8023_1000BASE_X = 255894466;
    public static final String _ieee8023_1000BASE_X_ = "ieee8023-1000BASE-X";
    public static final int    _ieee8023_1000BASE_PX10 = 1804696473;
    public static final String _ieee8023_1000BASE_PX10_ = "ieee8023-1000BASE-PX10";
    public static final int    _ieee8023_1000BASE_PX20 = 467369965;
    public static final String _ieee8023_1000BASE_PX20_ = "ieee8023-1000BASE-PX20";
    public static final int    _ieee8023_100BASE_X = 1253477639;
    public static final String _ieee8023_100BASE_X_ = "ieee8023-100BASE-X";
    public static final int    _ieee8023_10BASE_Te = 673799919;
    public static final String _ieee8023_10BASE_Te_ = "ieee8023-10BASE-Te";
    public static final int    _ieee8023_10GBASE_EW = 1069776239;
    public static final String _ieee8023_10GBASE_EW_ = "ieee8023-10GBASE-EW";
    public static final int    _ieee8023_10BASE_FB = 10628825;
    public static final String _ieee8023_10BASE_FB_ = "ieee8023-10BASE-FB";
    public static final int    _ieee8023_10BASE_FL = 108319190;
    public static final String _ieee8023_10BASE_FL_ = "ieee8023-10BASE-FL";
    public static final int    _ieee8023_1000BASE_BX10 = 2115759179;
    public static final String _ieee8023_1000BASE_BX10_ = "ieee8023-1000BASE-BX10";
    public static final int    _ieee8023_10GBASE_L = 2060457591;
    public static final String _ieee8023_10GBASE_L_ = "ieee8023-10GBASE-L";
    public static final int    _ieee8023_10BASE_FP = 1280532729;
    public static final String _ieee8023_10BASE_FP_ = "ieee8023-10BASE-FP";
    public static final int    _ieee8023_1000BASE_T = 1490223622;
    public static final String _ieee8023_1000BASE_T_ = "ieee8023-1000BASE-T";
    public static final int    _ieee8023_1000BASE_CX = 763261821;
    public static final String _ieee8023_1000BASE_CX_ = "ieee8023-1000BASE-CX";
    public static final int    _ieee8023_100BASE_FX = 77832807;
    public static final String _ieee8023_100BASE_FX_ = "ieee8023-100BASE-FX";
}
