/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ifmgr-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ifmgr-cfg.yang */
public class CiscoIOSXRIfmgrCfg extends ConfNamespace {
    public static final int hash = 1984872371;
    public int hash() {
        return CiscoIOSXRIfmgrCfg.hash;
    }

    public static final String id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg";
    public String id() {
        return CiscoIOSXRIfmgrCfg.id;
    }

    public static final String uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg";
    public String uri() {
        return CiscoIOSXRIfmgrCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIfmgrCfg.uri);
    }

    public static final String prefix = "ifmgr-cfg";
    public String prefix() {
        return CiscoIOSXRIfmgrCfg.prefix;
    }

    public CiscoIOSXRIfmgrCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _interface_mode_non_physical = 1525547646;
    public static final String _interface_mode_non_physical_ = "interface-mode-non-physical";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _args = 578380655;
    public static final String _args_ = "args";
    public static final int    _link_status = 2137463011;
    public static final String _link_status_ = "link-status";
    public static final int    _shutdown = 460723287;
    public static final String _shutdown_ = "shutdown";
    public static final int    _suppress_time = 1030211810;
    public static final String _suppress_time_ = "suppress-time";
    public static final int    _interface_configuration = 1340857377;
    public static final String _interface_configuration_ = "interface-configuration";
    public static final int    _dampening = 1049243107;
    public static final String _dampening_ = "dampening";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _mtus = 1903045155;
    public static final String _mtus_ = "mtus";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _suppress_threshold = 1022099602;
    public static final String _suppress_threshold_ = "suppress-threshold";
    public static final int    _capsulation_options = 1165673411;
    public static final String _capsulation_options_ = "capsulation-options";
    public static final int    _interface_virtual = 366954786;
    public static final String _interface_virtual_ = "interface-virtual";
    public static final int    _global_interface_configuration = 628731272;
    public static final String _global_interface_configuration_ = "global-interface-configuration";
    public static final int    _secondary_admin_state = 2116682695;
    public static final String _secondary_admin_state_ = "secondary-admin-state";
    public static final int    _bandwidth = 82191353;
    public static final String _bandwidth_ = "bandwidth";
    public static final int    _half_life = 722675026;
    public static final String _half_life_ = "half-life";
    public static final int    _owner = 206925960;
    public static final String _owner_ = "owner";
    public static final int    _encapsulation = 436115321;
    public static final String _encapsulation_ = "encapsulation";
    public static final int    _restart_penalty = 354955372;
    public static final String _restart_penalty_ = "restart-penalty";
    public static final int    _active = 124277386;
    public static final String _active_ = "active";
    public static final int    _interface_configurations = 1818562055;
    public static final String _interface_configurations_ = "interface-configurations";
    public static final int    _reuse_threshold = 1727092908;
    public static final String _reuse_threshold_ = "reuse-threshold";
}
