/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-l2-eth-infra-datatypes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-l2-eth-infra-datatypes.yang */
public class CiscoIOSXRL2EthInfraDatatypes extends ConfNamespace {
    public static final int hash = 200921995;
    public int hash() {
        return CiscoIOSXRL2EthInfraDatatypes.hash;
    }

    public static final String id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-datatypes";
    public String id() {
        return CiscoIOSXRL2EthInfraDatatypes.id;
    }

    public static final String uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-datatypes";
    public String uri() {
        return CiscoIOSXRL2EthInfraDatatypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRL2EthInfraDatatypes.uri);
    }

    public static final String prefix = "l2-eth-infra-datatypes";
    public String prefix() {
        return CiscoIOSXRL2EthInfraDatatypes.prefix;
    }

    public CiscoIOSXRL2EthInfraDatatypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
