/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-l2-eth-infra-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-l2-eth-infra-cfg.yang */
public class CiscoIOSXRL2EthInfraCfg extends ConfNamespace {
    public static final int hash = 206665423;
    public int hash() {
        return CiscoIOSXRL2EthInfraCfg.hash;
    }

    public static final String id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-cfg";
    public String id() {
        return CiscoIOSXRL2EthInfraCfg.id;
    }

    public static final String uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-l2-eth-infra-cfg";
    public String uri() {
        return CiscoIOSXRL2EthInfraCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRL2EthInfraCfg.uri);
    }

    public static final String prefix = "l2-eth-infra-cfg";
    public String prefix() {
        return CiscoIOSXRL2EthInfraCfg.prefix;
    }

    public CiscoIOSXRL2EthInfraCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _native_vlan_identifier = 2017212990;
    public static final String _native_vlan_identifier_ = "native-vlan-identifier";
    public static final int    _l2_protocol = 1647255608;
    public static final String _l2_protocol_ = "l2-protocol";
    public static final int    _outer_vlan_id = 2008251797;
    public static final String _outer_vlan_id_ = "outer-vlan-id";
    public static final int    _additional_range5_high = 2017647218;
    public static final String _additional_range5_high_ = "additional-range5-high";
    public static final int    _additional_range4_low = 1743114047;
    public static final String _additional_range4_low_ = "additional-range4-low";
    public static final int    _inner_vlan_id = 333468475;
    public static final String _inner_vlan_id_ = "inner-vlan-id";
    public static final int    _mpls_exp_bits_value = 93798753;
    public static final String _mpls_exp_bits_value_ = "mpls-exp-bits-value";
    public static final int    _additional_range2_low = 1783336901;
    public static final String _additional_range2_low_ = "additional-range2-low";
    public static final int    _additional_range6_high = 1003814144;
    public static final String _additional_range6_high_ = "additional-range6-high";
    public static final int    _additional_range3_high = 1105957914;
    public static final String _additional_range3_high_ = "additional-range3-high";
    public static final int    _ethernet_bng = 2121426884;
    public static final String _ethernet_bng_ = "ethernet-bng";
    public static final int    _l2_protocols = 1594663027;
    public static final String _l2_protocols_ = "l2-protocols";
    public static final int    _inner_class_of_service = 1950021607;
    public static final String _inner_class_of_service_ = "inner-class-of-service";
    public static final int    _mac_accounting = 1100121058;
    public static final String _mac_accounting_ = "mac-accounting";
    public static final int    _egress = 124484228;
    public static final String _egress_ = "egress";
    public static final int    _first_tag = 1064947953;
    public static final String _first_tag_ = "first-tag";
    public static final int    _tunneling_ethertype = 336671766;
    public static final String _tunneling_ethertype_ = "tunneling-ethertype";
    public static final int    _ingress = 1440811799;
    public static final String _ingress_ = "ingress";
    public static final int    _additional_range8_high = 1731893482;
    public static final String _additional_range8_high_ = "additional-range8-high";
    public static final int    _additional_range7_low = 213036360;
    public static final String _additional_range7_low_ = "additional-range7-low";
    public static final int    _additional_range4_high = 1620358896;
    public static final String _additional_range4_high_ = "additional-range4-high";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _exact = 1904427471;
    public static final String _exact_ = "exact";
    public static final int    _rewrite_type = 886922036;
    public static final String _rewrite_type_ = "rewrite-type";
    public static final int    _propagate_remote_status = 1251179270;
    public static final String _propagate_remote_status_ = "propagate-remote-status";
    public static final int    _additional_range6_low = 1820350089;
    public static final String _additional_range6_low_ = "additional-range6-low";
    public static final int    _vlan_identifier = 1083596707;
    public static final String _vlan_identifier_ = "vlan-identifier";
    public static final int    _ingress_destination_mac = 724777351;
    public static final String _ingress_destination_mac_ = "ingress-destination-mac";
    public static final int    _outer_tag_type = 1606211431;
    public static final String _outer_tag_type_ = "outer-tag-type";
    public static final int    _egress_filtering_default_on = 335695710;
    public static final String _egress_filtering_default_on_ = "egress-filtering-default-on";
    public static final int    _vlan_type = 1462572752;
    public static final String _vlan_type_ = "vlan-type";
    public static final int    _payload_ethertype_match = 815900945;
    public static final String _payload_ethertype_match_ = "payload-ethertype-match";
    public static final int    _additional_range2_high = 1385880240;
    public static final String _additional_range2_high_ = "additional-range2-high";
    public static final int    _filtering = 1898988778;
    public static final String _filtering_ = "filtering";
    public static final int    _local_traffic_default_encapsulation = 265924167;
    public static final String _local_traffic_default_encapsulation_ = "local-traffic-default-encapsulation";
    public static final int    _additional_range8_low = 1451518172;
    public static final String _additional_range8_low_ = "additional-range8-low";
    public static final int    _ingress_source_mac = 1347845593;
    public static final String _ingress_source_mac_ = "ingress-source-mac";
    public static final int    _ethernet_service = 1420656229;
    public static final String _ethernet_service_ = "ethernet-service";
    public static final int    _additional_range1_high = 117965460;
    public static final String _additional_range1_high_ = "additional-range1-high";
    public static final int    _outer_tag_value = 909697216;
    public static final String _outer_tag_value_ = "outer-tag-value";
    public static final int    _outer_range1_high = 1891165642;
    public static final String _outer_range1_high_ = "outer-range1-high";
    public static final int    _inner_tag_type = 702580091;
    public static final String _inner_tag_type_ = "inner-tag-type";
    public static final int    _additional_range7_high = 888335060;
    public static final String _additional_range7_high_ = "additional-range7-high";
    public static final int    _source_bypass_egress_filtering = 266015899;
    public static final String _source_bypass_egress_filtering_ = "source-bypass-egress-filtering";
    public static final int    _egress_filtering = 1610075207;
    public static final String _egress_filtering_ = "egress-filtering";
    public static final int    _l2_ethernet_features = 1984863197;
    public static final String _l2_ethernet_features_ = "l2-ethernet-features";
    public static final int    _inner_tag_value = 259748574;
    public static final String _inner_tag_value_ = "inner-tag-value";
    public static final int    _additional_range1_low = 158391929;
    public static final String _additional_range1_low_ = "additional-range1-low";
    public static final int    _l2_protocol_name = 574710523;
    public static final String _l2_protocol_name_ = "l2-protocol-name";
    public static final int    _outer_range1_low = 1538429562;
    public static final String _outer_range1_low_ = "outer-range1-low";
    public static final int    _inner_range1_high = 637544758;
    public static final String _inner_range1_high_ = "inner-range1-high";
    public static final int    _vlan_sub_configuration = 1871136408;
    public static final String _vlan_sub_configuration_ = "vlan-sub-configuration";
    public static final int    _rewrite = 166816274;
    public static final String _rewrite_ = "rewrite";
    public static final int    _second_tag = 1851784776;
    public static final String _second_tag_ = "second-tag";
    public static final int    _additional_range5_low = 1937177320;
    public static final String _additional_range5_low_ = "additional-range5-low";
    public static final int    _ambiguous_encapsulation = 1008577732;
    public static final String _ambiguous_encapsulation_ = "ambiguous-encapsulation";
    public static final int    _outer_class_of_service = 377301823;
    public static final String _outer_class_of_service_ = "outer-class-of-service";
    public static final int    _inner_range1_low = 692194849;
    public static final String _inner_range1_low_ = "inner-range1-low";
    public static final int    _ethernet_features = 438459691;
    public static final String _ethernet_features_ = "ethernet-features";
    public static final int    _encapsulation = 436115321;
    public static final String _encapsulation_ = "encapsulation";
    public static final int    _additional_range3_low = 608538218;
    public static final String _additional_range3_low_ = "additional-range3-low";
    public static final int    _vlan_trunk_configuration = 1190185368;
    public static final String _vlan_trunk_configuration_ = "vlan-trunk-configuration";
}
