/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-types.yang */
public class CiscoIOSXRTypes extends ConfNamespace {
    public static final int hash = 383236521;
    public int hash() {
        return CiscoIOSXRTypes.hash;
    }

    public static final String id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/cisco-xr-types";
    public String id() {
        return CiscoIOSXRTypes.id;
    }

    public static final String uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/cisco-xr-types";
    public String uri() {
        return CiscoIOSXRTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRTypes.uri);
    }

    public static final String prefix = "xr";
    public String prefix() {
        return CiscoIOSXRTypes.prefix;
    }

    public CiscoIOSXRTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
