/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/Cisco-IOS-XR-ip-static-cfg.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-static-cfg.yang */
public class CiscoIOSXRIpStaticCfg extends ConfNamespace {
    public static final int hash = 301866303;
    public int hash() {
        return CiscoIOSXRIpStaticCfg.hash;
    }

    public static final String id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg";
    public String id() {
        return CiscoIOSXRIpStaticCfg.id;
    }

    public static final String uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg";
    public String uri() {
        return CiscoIOSXRIpStaticCfg.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(CiscoIOSXRIpStaticCfg.uri);
    }

    public static final String prefix = "ip-static-cfg";
    public String prefix() {
        return CiscoIOSXRIpStaticCfg.prefix;
    }

    public CiscoIOSXRIpStaticCfg() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _vrfipv6 = 954599956;
    public static final String _vrfipv6_ = "vrfipv6";
    public static final int    _vrf_route = 889408751;
    public static final String _vrf_route_ = "vrf-route";
    public static final int    _prefix = 1408440115;
    public static final String _prefix_ = "prefix";
    public static final int    _ipv6_routes = 1616945530;
    public static final String _ipv6_routes_ = "ipv6-routes";
    public static final int    _vrf_multicast = 1375743423;
    public static final String _vrf_multicast_ = "vrf-multicast";
    public static final int    _vrf_prefix = 1782033892;
    public static final String _vrf_prefix_ = "vrf-prefix";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _default_vrf = 1381354774;
    public static final String _default_vrf_ = "default-vrf";
    public static final int    _minimum_interval = 1685631107;
    public static final String _minimum_interval_ = "minimum-interval";
    public static final int    _detect_multiplier = 25443398;
    public static final String _detect_multiplier_ = "detect-multiplier";
    public static final int    _vrf_next_hop_table = 808762042;
    public static final String _vrf_next_hop_table_ = "vrf-next-hop-table";
    public static final int    _default_topology = 2049256514;
    public static final String _default_topology_ = "default-topology";
    public static final int    _vrf = 1281310328;
    public static final String _vrf_ = "vrf";
    public static final int    _segment_route_next_hop_table = 136384006;
    public static final String _segment_route_next_hop_table_ = "segment-route-next-hop-table";
    public static final int    _next_hop_address = 88257637;
    public static final String _next_hop_address_ = "next-hop-address";
    public static final int    _ipv4_routes = 110884886;
    public static final String _ipv4_routes_ = "ipv4-routes";
    public static final int    _maximum_routes = 996759931;
    public static final String _maximum_routes_ = "maximum-routes";
    public static final int    _load_metric = 925265492;
    public static final String _load_metric_ = "load-metric";
    public static final int    _vrfipv4 = 270489138;
    public static final String _vrfipv4_ = "vrfipv4";
    public static final int    _address_family = 203507431;
    public static final String _address_family_ = "address-family";
    public static final int    _vrf_next_hop_interface_name_next_hop_address = 1770512573;
    public static final String _vrf_next_hop_interface_name_next_hop_address_ = "vrf-next-hop-interface-name-next-hop-address";
    public static final int    _topology = 333175635;
    public static final String _topology_ = "topology";
    public static final int    _vrf_prefix_topologies = 958490142;
    public static final String _vrf_prefix_topologies_ = "vrf-prefix-topologies";
    public static final int    _metric = 235154778;
    public static final String _metric_ = "metric";
    public static final int    _interface_name = 1322899300;
    public static final String _interface_name_ = "interface-name";
    public static final int    _vrf_next_hop_interface_name = 576391683;
    public static final String _vrf_next_hop_interface_name_ = "vrf-next-hop-interface-name";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _vrf_name = 2140916904;
    public static final String _vrf_name_ = "vrf-name";
    public static final int    _vrf_prefixes = 891399128;
    public static final String _vrf_prefixes_ = "vrf-prefixes";
    public static final int    _permanent = 828170346;
    public static final String _permanent_ = "permanent";
    public static final int    _tunnel_id = 861555660;
    public static final String _tunnel_id_ = "tunnel-id";
    public static final int    _explicit_path_name = 1866287822;
    public static final String _explicit_path_name_ = "explicit-path-name";
    public static final int    _topologies = 379567156;
    public static final String _topologies_ = "topologies";
    public static final int    _topology_name = 595636554;
    public static final String _topology_name_ = "topology-name";
    public static final int    _router_static = 100858709;
    public static final String _router_static_ = "router-static";
    public static final int    _vrf_unicast = 1871092439;
    public static final String _vrf_unicast_ = "vrf-unicast";
    public static final int    _vrf_seg_route = 1825456538;
    public static final String _vrf_seg_route_ = "vrf-seg-route";
    public static final int    _vrf_next_hop_next_hop_address = 1865061679;
    public static final String _vrf_next_hop_next_hop_address_ = "vrf-next-hop-next-hop-address";
    public static final int    _bfd_fast_detect = 532395595;
    public static final String _bfd_fast_detect_ = "bfd-fast-detect";
    public static final int    _vrfs = 777611836;
    public static final String _vrfs_ = "vrfs";
    public static final int    _vrf_prefix_topology = 342526293;
    public static final String _vrf_prefix_topology_ = "vrf-prefix-topology";
    public static final int    _object_name = 657753792;
    public static final String _object_name_ = "object-name";
    public static final int    _vrf_next_hop_next_hop_address_explicit_path_name = 533288328;
    public static final String _vrf_next_hop_next_hop_address_explicit_path_name_ = "vrf-next-hop-next-hop-address-explicit-path-name";
    public static final int    _vrf_next_hop_explicit_path_name = 453459231;
    public static final String _vrf_next_hop_explicit_path_name_ = "vrf-next-hop-explicit-path-name";
    public static final int    _vrf_lable = 138790253;
    public static final String _vrf_lable_ = "vrf-lable";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
