/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nc.yang */
public class tailfNedIdCiscoNc extends ConfNamespace {
    public static final int hash = 1634026686;
    public int hash() {
        return tailfNedIdCiscoNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nc";
    public String id() {
        return tailfNedIdCiscoNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nc";
    public String uri() {
        return tailfNedIdCiscoNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNc.uri);
    }

    public static final String prefix = "cisco-nc";
    public String prefix() {
        return tailfNedIdCiscoNc.prefix;
    }

    public tailfNedIdCiscoNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nc = 1207132395;
    public static final String _cisco_nc_ = "cisco-nc";
    public static final int    ned_id = 1207132395;
    public static final String ned_id_ = "cisco-nc:cisco-nc";
}
