/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisco.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nc-1.0.yang */
public class tailfNedIdCiscoNc1_0 extends ConfNamespace {
    public static final int hash = 2011875503;
    public int hash() {
        return tailfNedIdCiscoNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nc-1.0";
    public String id() {
        return tailfNedIdCiscoNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nc-1.0";
    public String uri() {
        return tailfNedIdCiscoNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNc1_0.uri);
    }

    public static final String prefix = "cisco-nc-1.0";
    public String prefix() {
        return tailfNedIdCiscoNc1_0.prefix;
    }

    public tailfNedIdCiscoNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nc_10x2e0 = 1413599745;
    public static final String _cisco_nc_10x2e0_ = "cisco-nc-1.0";
}
