#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Cisco-IOS-XR-ip-static-cfg.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Cisco-IOS-XR-ip-static-cfg.yang


class ns(object):
    hash = 301866303

    id = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg"

    uri = "_cisco-nc-1.0:cisco-nc-1.0#http://cisco.com/ns/yang/Cisco-IOS-XR-ip-static-cfg"

    prefix = "ip-static-cfg"

    ip_static_cfg_vrfipv6 = 954599956
    ip_static_cfg_vrfipv6_ = "vrfipv6"
    ip_static_cfg_vrf_route = 889408751
    ip_static_cfg_vrf_route_ = "vrf-route"
    ip_static_cfg_prefix = 1408440115
    ip_static_cfg_prefix_ = "prefix"
    ip_static_cfg_ipv6_routes = 1616945530
    ip_static_cfg_ipv6_routes_ = "ipv6-routes"
    ip_static_cfg_vrf_multicast = 1375743423
    ip_static_cfg_vrf_multicast_ = "vrf-multicast"
    ip_static_cfg_vrf_prefix = 1782033892
    ip_static_cfg_vrf_prefix_ = "vrf-prefix"
    ip_static_cfg_tag = 21925559
    ip_static_cfg_tag_ = "tag"
    ip_static_cfg_default_vrf = 1381354774
    ip_static_cfg_default_vrf_ = "default-vrf"
    ip_static_cfg_minimum_interval = 1685631107
    ip_static_cfg_minimum_interval_ = "minimum-interval"
    ip_static_cfg_detect_multiplier = 25443398
    ip_static_cfg_detect_multiplier_ = "detect-multiplier"
    ip_static_cfg_vrf_next_hop_table = 808762042
    ip_static_cfg_vrf_next_hop_table_ = "vrf-next-hop-table"
    ip_static_cfg_default_topology = 2049256514
    ip_static_cfg_default_topology_ = "default-topology"
    ip_static_cfg_vrf = 1281310328
    ip_static_cfg_vrf_ = "vrf"
    ip_static_cfg_segment_route_next_hop_table = 136384006
    ip_static_cfg_segment_route_next_hop_table_ = "segment-route-next-hop-table"
    ip_static_cfg_next_hop_address = 88257637
    ip_static_cfg_next_hop_address_ = "next-hop-address"
    ip_static_cfg_ipv4_routes = 110884886
    ip_static_cfg_ipv4_routes_ = "ipv4-routes"
    ip_static_cfg_maximum_routes = 996759931
    ip_static_cfg_maximum_routes_ = "maximum-routes"
    ip_static_cfg_load_metric = 925265492
    ip_static_cfg_load_metric_ = "load-metric"
    ip_static_cfg_vrfipv4 = 270489138
    ip_static_cfg_vrfipv4_ = "vrfipv4"
    ip_static_cfg_address_family = 203507431
    ip_static_cfg_address_family_ = "address-family"
    ip_static_cfg_vrf_next_hop_interface_name_next_hop_address = 1770512573
    ip_static_cfg_vrf_next_hop_interface_name_next_hop_address_ = "vrf-next-hop-interface-name-next-hop-address"
    ip_static_cfg_topology = 333175635
    ip_static_cfg_topology_ = "topology"
    ip_static_cfg_vrf_prefix_topologies = 958490142
    ip_static_cfg_vrf_prefix_topologies_ = "vrf-prefix-topologies"
    ip_static_cfg_metric = 235154778
    ip_static_cfg_metric_ = "metric"
    ip_static_cfg_interface_name = 1322899300
    ip_static_cfg_interface_name_ = "interface-name"
    ip_static_cfg_vrf_next_hop_interface_name = 576391683
    ip_static_cfg_vrf_next_hop_interface_name_ = "vrf-next-hop-interface-name"
    ip_static_cfg_description = 202559156
    ip_static_cfg_description_ = "description"
    ip_static_cfg_vrf_name = 2140916904
    ip_static_cfg_vrf_name_ = "vrf-name"
    ip_static_cfg_vrf_prefixes = 891399128
    ip_static_cfg_vrf_prefixes_ = "vrf-prefixes"
    ip_static_cfg_permanent = 828170346
    ip_static_cfg_permanent_ = "permanent"
    ip_static_cfg_tunnel_id = 861555660
    ip_static_cfg_tunnel_id_ = "tunnel-id"
    ip_static_cfg_explicit_path_name = 1866287822
    ip_static_cfg_explicit_path_name_ = "explicit-path-name"
    ip_static_cfg_topologies = 379567156
    ip_static_cfg_topologies_ = "topologies"
    ip_static_cfg_topology_name = 595636554
    ip_static_cfg_topology_name_ = "topology-name"
    ip_static_cfg_router_static = 100858709
    ip_static_cfg_router_static_ = "router-static"
    ip_static_cfg_vrf_unicast = 1871092439
    ip_static_cfg_vrf_unicast_ = "vrf-unicast"
    ip_static_cfg_vrf_seg_route = 1825456538
    ip_static_cfg_vrf_seg_route_ = "vrf-seg-route"
    ip_static_cfg_vrf_next_hop_next_hop_address = 1865061679
    ip_static_cfg_vrf_next_hop_next_hop_address_ = "vrf-next-hop-next-hop-address"
    ip_static_cfg_bfd_fast_detect = 532395595
    ip_static_cfg_bfd_fast_detect_ = "bfd-fast-detect"
    ip_static_cfg_vrfs = 777611836
    ip_static_cfg_vrfs_ = "vrfs"
    ip_static_cfg_vrf_prefix_topology = 342526293
    ip_static_cfg_vrf_prefix_topology_ = "vrf-prefix-topology"
    ip_static_cfg_object_name = 657753792
    ip_static_cfg_object_name_ = "object-name"
    ip_static_cfg_vrf_next_hop_next_hop_address_explicit_path_name = 533288328
    ip_static_cfg_vrf_next_hop_next_hop_address_explicit_path_name_ = "vrf-next-hop-next-hop-address-explicit-path-name"
    ip_static_cfg_vrf_next_hop_explicit_path_name = 453459231
    ip_static_cfg_vrf_next_hop_explicit_path_name_ = "vrf-next-hop-explicit-path-name"
    ip_static_cfg_vrf_lable = 138790253
    ip_static_cfg_vrf_lable_ = "vrf-lable"
    ip_static_cfg_prefix_length = 524393771
    ip_static_cfg_prefix_length_ = "prefix-length"
